### ISSUE TITLE
Please upgrade Neo4j ETL to support data with Chinese character

### ISSUE THREAD

**Issue by SuperLat** [neo4j-contrib/neo4j-etl#52] opened 2019-05-30 08:57 UTC
@jexp 
Hi. I am using Neo4j ETL to immigrate data ,whicn contains Chinese character, from oracle to Neo4j.  Two issues encounted , and hope you can upgrade the ETL tool to slove these two issues. 
Issue 1：If using ETL tool to immigrate data with Chinese character, the UI display with messy code. My solution is to modify csv in UTF-8 format manually. Thus my expection is add a UI option to support to careate UTF-8 format csv.
Issue 2:In relationship UI，the entityname modificaiton input is not stable. Sometimes I can modify all entitynames, sometimes I can't modify  the first entityname. In addition ,if I modify entityname with Chinese character, the relationship can't be saved, which makes the UI display empty.
![微信图片_20190530165715](https://user-images.githubusercontent.com/51182043/58621451-017f4c00-82fc-11e9-9525-a51b92dec4fd.png)
![微信图片_20190530165907](https://user-images.githubusercontent.com/51182043/58621577-473c1480-82fc-11e9-9941-8f97caa8d0f2.png)

**Comment by conker84** [comment] 2019-09-14 19:36
Duplicate of #51

**Closed by conker84** 2019-09-14 19:36 UTC
