### ISSUE TITLE
Mapping shows the previous mapping, not the one just generated

### ISSUE THREAD

**Issue by davidlrosenblum** [neo4j-contrib/neo4j-etl#15] opened 2018-03-23 16:04 UTC
To reproduce, create two connections.  First map one of the connections, click next, import.
Close the ETL tool.
Reopen the ETL tool.
Select the other connection.
Click Start Mapping
Previous mapping will show
Clicking Next will show the tables and columns and the node diagram from the first mapping.

**Comment by omarlarus** [comment] 2018-03-28 17:12
Hi @davidlrosenblum ,
I cannot reproduce this issue. Can you provide us any further information?
- the connection names
- the connectoin driver types
- the ETL and neo4j desktop version 
- the Operation System 

Thanks

**Comment by albertodelazzari** [comment] 2018-03-29 08:46
We are not able to reproduce the issue using a MacOS, are you using a Windows OS?

**Comment by albertodelazzari** [comment] 2018-06-21 09:32
I think we can close this issue

**Closed** 2018-07-04 19:04 UTC
